# -*- coding: utf-8 -*-
"""Week2Day6_Ex.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LlnkUUe_RCVYrVeRVaEqtlBpUzwGxXoj

Apolo Barnabas
Week2_day6_Ex
"""

# Exercise 1: Cats
# Define the Cat class
class Cat:
    def __init__(self, name, age):
        self.name = name
        self.age = age

# Create three cat objects
cat1 = Cat("Milo", 6)
cat2 = Cat("Luna", 8)
cat3 = Cat("Simba", 3)

# Print their details
print(cat1.name, cat1.age)
print(cat2.name, cat2.age)
print(cat3.name, cat3.age)

# Function to find the oldest cat
def find_oldest_cat(cat1, cat2, cat3):
    oldest = cat1

    if cat2.age > oldest.age:
        oldest = cat2

    if cat3.age > oldest.age:
        oldest = cat3

    return oldest


# Call the function
oldest_cat = find_oldest_cat(cat1, cat2, cat3)

# Print the formatted string
print(f"The oldest cat is {oldest_cat.name}, and is {oldest_cat.age} years old.")

#
class Dog:
    def __init__(self, name, height):
        self.name = name
        self.height = height

    def bark(self):
        print(f"{self.name} goes woof!")

    def jump(self):
        print(f"{self.name} jumps {self.height * 2} cm high!")


# Example
dog1 = Dog("Buddy", 50)

dog1.bark()
dog1.jump()

# Exercise 2
# Create Dog objects
davids_dog = Dog("David", 60)
sarahs_dog = Dog("Sarah", 45)

# Print David's dog information
print(davids_dog.name)
print(davids_dog.height)

davids_dog.bark()
davids_dog.jump()

# Print Sarah's dog information
print(sarahs_dog.name)
print(sarahs_dog.height)

sarahs_dog.bark()
sarahs_dog.jump()

# Compare the sizes of the dogs
if davids_dog.height > sarahs_dog.height:
    print(f"{davids_dog.name}'s dog is bigger.")
elif sarahs_dog.height > davids_dog.height:
    print(f"{sarahs_dog.name}'s dog is bigger.")
else:
    print("Both dogs are the same size.")

#  Exercise 3 : Who’s the song producer?
class Song:
    def __init__(self, lyrics):
        self.lyrics = lyrics

    def sing_me_a_song(self):
        for line in self.lyrics:
            print(line)


# Example
stairway = Song([
    "Chez nous au ciel",
    "Nous chanterons avec les anges",
    "Nous oublirons tout de ce monde"
])

stairway.sing_me_a_song()

# Exercise 4 : Afternoon at the Zoo

class Zoo:
    def __init__(self, zoo_name):
        self.zoo_name = zoo_name
        self.animals = []

    def add_animal(self, animal):
        if animal not in self.animals:
            self.animals.append(animal)

    def get_animals(self):
        for animal in self.animals:
            print(animal)

    def remove_animal(self, animal):
        if animal in self.animals:
            self.animals.remove(animal)

    def sort_animals(self):
        grouped_animals = {}

        # sort animals alphabetically first
        sorted_animals = sorted(self.animals)

        # group by first letter
        for animal in sorted_animals:
            first_letter = animal[0].upper()
            if first_letter not in grouped_animals:
                grouped_animals[first_letter] = []
            grouped_animals[first_letter].append(animal)

        return grouped_animals

    def get_groups(self):
        grouped = self.sort_animals()
        for letter, animals_list in grouped.items():
            print(f"{letter}: {animals_list}")

class Zoo:
    def __init__(self, zoo_name):
        self.zoo_name = zoo_name
        self.animals = []

    def add_animal(self, animal):
        if animal not in self.animals:
            self.animals.append(animal)

    def get_animals(self):
        for animal in self.animals:
            print(animal)

    def remove_animal(self, animal):
        if animal in self.animals:
            self.animals.remove(animal)

    def sort_animals(self):
        grouped_animals = {}

        # sort animals alphabetically first
        sorted_animals = sorted(self.animals)

        # group by first letter
        for animal in sorted_animals:
            first_letter = animal[0].upper()
            if first_letter not in grouped_animals:
                grouped_animals[first_letter] = []
            grouped_animals[first_letter].append(animal)

        return grouped_animals

    def get_groups(self):
        grouped = self.sort_animals()
        for letter, animals_list in grouped.items():
            print(f"{letter}: {animals_list}")

class Zoo:
    def __init__(self, zoo_name):
        self.zoo_name = zoo_name
        self.animals = []

    def add_animal(self, animal):
        if animal not in self.animals:
            self.animals.append(animal)

    def get_animals(self):
        for animal in self.animals:
            print(animal)

    def remove_animal(self, animal):
        if animal in self.animals:
            self.animals.remove(animal)

    def sort_animals(self):
        grouped_animals = {}
        sorted_animals = sorted(self.animals)

        for animal in sorted_animals:
            first_letter = animal[0].upper()
            if first_letter not in grouped_animals:
                grouped_animals[first_letter] = []
            grouped_animals[first_letter].append(animal)

        return grouped_animals

    def get_groups(self):
        grouped = self.sort_animals()

        for letter, animals_list in grouped.items():
            print(f"{letter}: {animals_list}")

my_zoo = Zoo("My Awesome Zoo")
print(my_zoo)

# Create a Zoo object
my_zoo = Zoo("Safari Park")

# Add animals
my_zoo.add_animal("Lion")
my_zoo.add_animal("Tiger")
my_zoo.add_animal("Bear")
my_zoo.add_animal("Giraffe")
my_zoo.add_animal("Gorilla")
my_zoo.add_animal("Goat")

# Display all animals
print("All animals in the zoo:")
my_zoo.get_animals()

# Remove an animal (selling equivalent)
my_zoo.remove_animal("Tiger")

print("\nAfter removing Tiger:")
my_zoo.get_animals()

# Sort and group animals
print("\nGrouped animals:")
groups = my_zoo.sort_animals()

for letter, animals in groups.items():
    print(f"{letter}: {animals}")

#Bonus
my_zoo = Zoo("Safari World")

my_zoo.add_animal("Lion")
my_zoo.add_animal("Tiger")
my_zoo.add_animal("Elephant")
my_zoo.add_animal("Giraffe")

print(my_zoo.animals)